# -*- coding: utf-8 -*-
"""#107 | Data Ananlysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ekqhAfcGdhuaTCpWE5sfY29jOCW3z4Km
"""

import csv
import pandas as pd
import plotly.graph_objects as go

df = pd.read_csv('data.csv')
# print(df.groupby("level")["attempt"].mean())

fig = go.Figure(go.Bar(
                  x = df.groupby("level")["attempt"].mean(),
                  y = ['Level 1', 'Level 2', 'Level 3', 'Level 4'],
                  orientation = 'h'
))

fig.show()

import csv
import pandas as pd
import plotly.graph_objects as go

df = pd.read_csv('data.csv')
student_df = df.loc[df['student_id'] == 'TRL_xsl']

fig = go.Figure(go.Bar(
                  x = df.groupby("level")["attempt"].mean(),
                  y = ['Level 1', 'Level 2', 'Level 3', 'Level 4'],
                  orientation = 'h'
))

fig.show()